from typing import List, Optional
from pydantic import BaseModel

# --- AI GENERATED SCHEMAS (Semantic Engine) ---
class JobRequirement(BaseModel):
    skill_name: str

class SkillsEvaluation(BaseModel):
    requirement_category: str
    job_requirements: List[JobRequirement]
    matched_cv_skills: List[str]
    missing_cv_skills: List[str]
    rationale: str

class CandidateRole(BaseModel):
    role_title: str
    start_date: Optional[str]
    end_date: Optional[str]
    match_rationale: str
    is_relevant: bool

class OverallExperience(BaseModel):
    target_job_title: str
    target_overall_years: Optional[float]
    candidate_roles: List[CandidateRole]

class SemanticOutput(BaseModel):
    """The strictly bounded output generated by Llama 3.2"""
    skills_evaluation: SkillsEvaluation
    overall_experience: OverallExperience

# --- PYTHON GENERATED SCHEMAS (Deterministic Engine) ---
class Pillar(BaseModel):
    score: float
    raw: str
    applicable: bool

class Scorecard(BaseModel):
    final_relevance: float
    pillar_a: Pillar
    pillar_b: Pillar
    counted_roles: List[str]

class Metrics(BaseModel):
    total_requirements: int
    total_matched: int
    match_percentage: float
    final_relevance: float

class Check(BaseModel):
    name: str
    expected: str
    actual: str
    passed: bool

class Evaluation(BaseModel):
    passed: bool
    checks: List[Check]

class FullGuestimatorOutput(BaseModel):
    """The final artifact combining AI semantics and Python math"""
    skills_evaluation: SkillsEvaluation
    overall_experience: OverallExperience
    scorecard: Scorecard
    metrics: Metrics
    evaluation: Evaluation